[package]
name = "ere-platform-pico"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# Pico dependencies
pico-sdk = { workspace = true, features = ["kb"] }

# Local dependencies
ere-platform-trait.workspace = true

[features]
default = []
libm = ["pico-sdk/libm"]

[lints]
workspace = true
