[package]
name = "ere-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["alloc", "derive"] }

[build-dependencies]
ere-build-utils.workspace = true
