[package]
name = "ere-platform-ziren"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# Ziren dependencies
zkm-zkvm.workspace = true

# Local dependencies
ere-platform-trait.workspace = true

[features]
default = ["libm", "bump"]
bump = ["zkm-zkvm/bump"]
embedded = ["zkm-zkvm/embedded"]
libm = ["zkm-zkvm/libm"]
verify = ["zkm-zkvm/verify"]

[lints]
workspace = true
