[package]
name = "ere-zisk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
bytemuck.workspace = true
serde.workspace = true
strum = { workspace = true, features = ["derive"] }
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
wait-timeout.workspace = true

# TODO: Move the workspace
futures-util = "0.3"
tokio = { version = "1", features = ["rt"] }
tonic = "0.14"
zisk-distributed-grpc-api = { git = "https://github.com/han0110/zisk", branch = "ere/v0.15.0" }

# Local dependencies
ere-compile-utils = { workspace = true, optional = true }
ere-zkvm-interface.workspace = true

[dev-dependencies]
ere-test-utils = { workspace = true, features = ["host"] }

[build-dependencies]
ere-build-utils.workspace = true

[features]
default = ["compiler", "zkvm"]
compiler = ["dep:ere-compile-utils"]
zkvm = []

[lints]
workspace = true
