[package]
name = "ere-platform-nexus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# Nexus dependencies
nexus-rt.workspace = true

# Local dependencies
ere-platform-trait.workspace = true

[features]
default = []

[lints]
workspace = true
