[package]
name = "ere-platform-trait"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
digest = { workspace = true, optional = true }

[features]
default = []
output-hasher = ["dep:digest"]

[lints]
workspace = true
