[package]
name = "ere-dockerized"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
parking_lot.workspace = true
serde = { workspace = true, features = ["derive"] }
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true

# Local dependencies
ere-zkvm-interface = { workspace = true, features = ["clap"] }
ere-common.workspace = true
ere-server.workspace = true

[dev-dependencies]
paste.workspace = true

# Local dependencies
ere-test-utils = { workspace = true, features = ["host"] }

[lints]
workspace = true
