name: Test and clippy ZisK

on:
  push:
    branches:
      - master
      - han/feature/zisk-network-prover
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test-zkvm.yml
    permissions:
      contents: read
      packages: write
    with:
      zkvm: zisk
      toolchain: 1.88.0
      skip_prove_test: true
